### ISSUE TITLE
Exclude @example from tag-lines

### ISSUE THREAD

**Issue by TheJaredWilcurt** [gajus/eslint-plugin-jsdoc#742] opened 2021-05-18 02:01 UTC
I have a lot of code like this:

```js
  /**
   * Generic validation method to ensure a specific key on a specific OS
   * object is either a string, or removed.
   *
   * @example
   * options = validateOptionalString(options, 'windows', 'comment');
   *
   * @param  {object} options          User's options
   * @param  {string} operatingSystem  'windows', 'linux', or 'osx'
   * @param  {string} key              The key within the OS object to be validated as an optional string
   * @return {object}                  Validated or mutated user options
   */
  validateOptionalString: function (options, operatingSystem, key) {
    //...
    return options;
  },
```

Notice that there is a clear separation between the method description, example, and param/return. The `tag-lines` rule treats `@example` the same as all other tags. But it looks messy without the extra return after the example.

Can we get a option for the tags to apply this to, maybe like how `check-line-alignment` does it?

**Comment by brettz9** [comment] 2021-05-18 02:08
Yeah, I've filed https://github.com/gajus/eslint-plugin-jsdoc/pull/741 for that purpose.

**Comment by brettz9** [comment] 2021-05-18 02:17
Closing as dupe of #734

**Closed by brettz9** 2021-05-18 02:17 UTC
Labels: enhancement
