### ISSUE TITLE
@link conflicts with require-description-complete-sentence

### ISSUE THREAD

**Issue by Aerendir** [gajus/eslint-plugin-jsdoc#72] opened 2018-05-04 08:39 UTC
I have this DocBlock:

```
/**
 * {@link https://github.com/ReactTraining/react-router/issues/4105#issuecomment-291834881}
 * {@link https://github.com/ReactTraining/react-router/issues/4105#issuecomment-294315922}
 *
 * @param {Object} props - The props passed.
 * ... Other @params
 * @returns {React.Component} - The Coommercio App.
 * @class
 */
```

I continue to receive the notice "Sentence must end with a period" (jsodc/require-description-complete-sentence).

Effectively I have not a dot in the end of my `@link` tags but this is because they are links.

According to [documentation](http://usejsdoc.org/tags-inline-link.html):

> If you don't provide any link text, JSDoc uses the namepath or URL as the link text.

Is this notice caused by this behavior?

I've also tried to add a description (just to "fix" the issue: I don't need it nor I want to add it) but the notice continues to be there:

```
 *
 * {@link https://github.com/ReactTraining/react-router/issues/4105#issuecomment-291834881|Issue.}
 * {@link https://github.com/ReactTraining/react-router/issues/4105#issuecomment-294315922|Issue.}
 *
```

More, If I use a more descriptive text like this I exceed the maximum line length (set at 100 chars):

```
 *
 * {@link https://github.com/ReactTraining/react-router/issues/4105#issuecomment-291834881|Issue #4105.}
 * {@link https://github.com/ReactTraining/react-router/issues/4105#issuecomment-294315922|Issue #4105.}
 *
```

- **How to format the tag if it exceeds the line length?**
- **How to fix the notice?**

**Comment by bary12** [comment] 2018-05-04 09:56
The rule should effectively ignore everything inside curly brackets. Does it work when you do `{@link https://some.url}.`? might just be a bug.

**Comment by Aerendir** [comment] 2018-05-04 11:12
This doesn't work: it continues to report the issue:

```
/**
 * {@link https://github.com}
 * {@link https://github.com}
 *
```

Can you try on you code and see if it really happens? Just to be sure the error exists and isn't something that depends on some faults of mine.

**Comment by brettz9** [comment] 2019-07-09 09:27
Yes, I can reproduce the behavior. However, I'm not sure we should really fix this.

For one, you can use the [`@see` tag](https://jsdoc.app/tags-see.html) instead if you really want a single line linking to something else and saying nothing else.

Secondly, as it is now, if you want to fit `{@link ...}` within a description, you can just add a period after the link, as @bary12 suggested, e.g., `{@link https://github.com}.`. If anything, imo, we should be reporting more here, so as to report that there is no initial capital letter in such cases, rather than trying to get rid of it reporting the lack of a period because the idea with `@link` is that, as an *inline* tag, it is supposed to be surrounded normally with other text, e.g.:

```
/**
 * Be sure to check out {@link https://github.com}.
*/
```

But as it is now, you can also do just this:

```
/**
 * {@link https://github.com}.
*/
```

**Comment by brettz9** [comment] 2019-12-01 06:02
Closing but feel free to comment further if needed.

**Closed by brettz9** 2019-12-01 06:02 UTC
Labels: question
