### ISSUE TITLE
warnings potentially fixable with the `--fix` option ?

### ISSUE THREAD

**Issue by PedroIssaGit** [gajus/eslint-plugin-jsdoc#760] opened 2021-06-28 12:43 UTC
How to enable --fix option in to jsdoc, to the plugin fix everything possible automatically ?

**Comment by PedroIssaGit** [comment] 2021-06-28 12:55
In my case, i'm using the latest 7.29.0 eslint version, with webpack, and i wanna to enable this plugin using eslint-webpack-plugin 2.5.4, when compiling with webpack/cli.

**Comment by brettz9** [comment] 2021-06-28 13:07
Some rules do not support doing so automatically. Some of these may be because it is not possible for us to know how you want to fix them, but often it is because we simply have not yet implemented fixers. See #336.

Closing as this is essentially a dupe of that issue, though feel free to comment further if desired.

**Closed by brettz9** 2021-06-28 13:07 UTC
Labels: documentation
