### ISSUE TITLE
[`check-template-names`] @property is ignored

### ISSUE THREAD

**Issue by regseb** [gajus/eslint-plugin-jsdoc#1269] opened 2024-07-20 11:19 UTC
## Expected behavior

_eslint-plugin-jsdoc_ should support two `@template` in one file.

## Actual behavior

```
Oops! Something went wrong! :(

ESLint: 9.7.0

Error: No parslet found for token: 'EOF'
Occurred while linting /home/regseb/testcase/index.js:1
Rule: "jsdoc/check-template-names"
    at Parser.parseIntermediateType (/home/regseb/testcase/node_modules/jsdoc-type-pratt-parser/dist/index.js:364:23)
    at Parser.parseType (/home/regseb/testcase/node_modules/jsdoc-type-pratt-parser/dist/index.js:355:42)
    at Parser.parse (/home/regseb/testcase/node_modules/jsdoc-type-pratt-parser/dist/index.js:345:33)
    at parse (/home/regseb/testcase/node_modules/jsdoc-type-pratt-parser/dist/index.js:1599:68)
    at iterateJsdoc.iterateAllJsdocs (file:///home/regseb/testcase/node_modules/eslint-plugin-jsdoc/src/rules/checkTemplateNames.js:70:5)
    at iterate (file:///home/regseb/testcase/node_modules/eslint-plugin-jsdoc/src/iterateJsdoc.js:2049:3)
    at callIterator (file:///home/regseb/testcase/node_modules/eslint-plugin-jsdoc/src/iterateJsdoc.js:2225:7)
    at Program:exit (file:///home/regseb/testcase/node_modules/eslint-plugin-jsdoc/src/iterateJsdoc.js:2318:11)
    at ruleErrorHandler (/home/regseb/testcase/node_modules/eslint/lib/linter/linter.js:1117:48)
    at /home/regseb/testcase/node_modules/eslint/lib/linter/safe-emitter.js:45:58
```

## ESLint Config

```javascript
import jsdoc from "eslint-plugin-jsdoc";

export default [
    {
        plugins: { jsdoc },
        rules: {
            "jsdoc/check-template-names": "error",
        }
    }
];
```

## ESLint sample

```js
/**
 * @template {Object} T
 * @typedef Foo<T>
 * @prop {T} bar
 */

/**
 * @template {Object} T
 * @typedef Baz<T>
 * @prop {T} qux
 */
```

## Environment

- Node version: v22.4.1
- ESLint version: v9.7.0
- `eslint-plugin-jsdoc` version: 48.8.1

**Comment by brettz9** [comment] 2024-07-20 11:36
The issue is apparently instead that a generic cannot be indicated in the name like this: `@typedef Foo<T>`. See the other examples for what is currently allowable.

Does TypeScript accept this form of JSDoc? I don't see it at https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#template .

**Comment by regseb** [comment] 2024-07-20 12:47
You're right, the error is reported with a single `@typedef`.

I tested the following file in [TS Playground](https://www.typescriptlang.org/play/?filetype=js#code/PQKhCgAIUgBAXApgWwA4BsCGTIG8DyARgFaIDG8AvpACpQwICeqiAJogGaQBiA9rwB58AVQAKAZQD6ASUkBZAIIBpAKKSFkmgE1R+AHz04qAE69UeGtUKZj9YOHCgI0OPGaI8fQQGd4xgJYAdgDmepR24GS8gb6QHPwAapjo-qyQALx4kNbGAFyQAEQFkJQA3A5OhkwsnvwCvgEhYRFRMfBx-NKBAG7JqRlZOfkADCXlFWBVSGhYOAQk5FS0U+7sXABCmABeVSZmFtQAjgCuAB4RjpMu1R64m1v1fkGh4dD2rbHWW0kpaZm4kBOp3yRTGE2cDDcNTu20ejReLWin22XV6vwGAKBIzGQA
). Without a generic or with an invalid generic, TypeScript returns the same errors (_number not assignable to string_). The `<T>` shouldn't be added to the `@typedef`.

```javascript
/**
 * @template {Object} T
 * @typedef Foo<OUPS_I_MAKE_A_TYPO>
 * @prop {T} bar
 */

/**
 * @type {Foo<string>}
 */
const fooValid = { bar: "" };

/**
 * @type {Foo<string>}
 */
const fooInvalid = { bar: 0 };
//                   ~~~


/**
 * @template {Object} T
 * @typedef Baz
 * @prop {T} qux
 */

/**
 * @type {Baz<string>}
 */
const bazValid = { qux: "" };

/**
 * @type {Baz<string>}
 */
const bazInvalid = { qux: 0 };
//                   ~~~
```

---

_eslint-plugin-jsdoc_ should report a syntax error for a JSDoc comment with `<T>`.

**Comment by brettz9** [comment] 2024-07-20 12:54
Yeah, I think that is a dupe of #374.

**Comment by regseb** [comment] 2024-07-20 12:59
The `No parslet found for token: 'EOF'` error isn't related to `@template`. I have the error with the following code.

```javascript
/**
 * @typedef Foo
 * @prop {string} bar
 */
```

And no error with:

```javascript
/**
 * @typedef {Object} Foo
 * @prop {string} bar
 */
```

**Comment by brettz9** [comment] 2024-07-20 13:11
Ah, great to know the playground can have tsconfig set to JavaScript. Wasn't aware of that.

I have confirmed the bug as you report now, yes. For now, I can change to silently ignore such parse errors here as when there is no type present, but I'll leave the issue open to try to handle the case for use of `@property` types. That sound reasonable?

**Closed** 2024-07-20 14:03 UTC
Labels: needs-feedback
