### ISSUE TITLE
Auto-fix require-jsdoc adds empty comments

### ISSUE THREAD

**Issue by bytroli** [gajus/eslint-plugin-jsdoc#594] opened 2020-06-25 21:02 UTC
Currently having `require-jsdoc` enabled and running the auto-fixer creates empty comment blocks which are worthless but pass the test for the rule. My suggestion would be to either not add those empty comment blocks or add an `enableFixer` option so this behaviour can optionally be disabled.

Configuration that triggers the above behaviour on auto-fix:
```
'jsdoc/require-jsdoc': ['warn', {
    publicOnly: false,
    require: {
        ArrowFunctionExpression: true,
        ClassDeclaration: true,
        ClassExpression: true,
        FunctionDeclaration: true,
        FunctionExpression: true,
        MethodDefinition: true,
    },
    exemptEmptyFunctions: false,
}],
```

**Comment by bytroli** [comment] 2020-06-25 21:23
Sorry, duplicate of https://github.com/gajus/eslint-plugin-jsdoc/issues/372. But there has been no resolve on that one. Perhaps it is now possible to add a `enableFixer` option to the rule similar to the require-* rules.

**Comment by brettz9** [comment] 2020-06-28 05:19
Sure, see my comment just now at https://github.com/gajus/eslint-plugin-jsdoc/issues/372#issuecomment-650698720 . Closing as indeed a dupe of #372.

**Closed by brettz9** 2020-06-28 05:19 UTC
Labels: enhancement
