### ISSUE TITLE
`sort-tags` section missing in README.md

### ISSUE THREAD

**Issue by thernstig** [gajus/eslint-plugin-jsdoc#987] opened 2023-02-14 10:49 UTC
See https://github.com/gajus/eslint-plugin-jsdoc#user-content-eslint-plugin-jsdoc-rules-sort-tags that links to nowhere.

**Comment by brettz9** [comment] 2023-02-14 13:16
Dupe of #886 .

**Closed by brettz9** 2023-02-14 13:16 UTC
Labels: documentation

**Comment by thernstig** [comment] 2023-02-14 14:24
Apologize for the dupe.
