### ISSUE TITLE
Global JSDoc in ESM imports do not count

### ISSUE THREAD

**Issue by michaelfig** [gajus/eslint-plugin-jsdoc#637] opened 2020-09-12 19:12 UTC
## Expected behavior

The plugin should be able to load global JSDoc types defined in different files, whether by ESM `import` or (as in the Typescript language server), just because they are in the same directory.

## Actual behavior

Typescript and the Typescript language server properly find the global JSDoc types in separate files.

For eslint-plugin-jsdoc, global JSDoc types in separate files are not loaded.  Types defined in them show up the IDE as:
![Screen Shot 2020-09-12 at 1 01 56 PM](https://user-images.githubusercontent.com/457244/93002994-2818c480-f4f8-11ea-8ff2-e88ec38c071e.png)
and in the eslint run as: https://gist.github.com/michaelfig/dc4c5665e9259f5316e35885567daa6b#file-eslint-log

This prevents modularity in defining types, but more importantly, this forces me to turn off the (otherwise useful) `jsdoc/no-undefined-types` rule to suppress the hundreds of false-positives I get.

## ESLint Config

https://gist.github.com/michaelfig/dc4c5665e9259f5316e35885567daa6b#file-package-json

## ESLint sample

https://gist.github.com/michaelfig/dc4c5665e9259f5316e35885567daa6b

## Environment

- Node version: 12.14.1
- ESLint version v7.8.1
- `eslint-plugin-jsdoc` version: 30.4.2

**Comment by brettz9** [comment] 2020-09-13 00:23
Dupe of #99 . That issue wouldn't address checking the same directory, but detection via `import` and other means, so closing.

**Closed by brettz9** 2020-09-13 00:23 UTC
Labels: bug-unconfirmed
