### ISSUE TITLE
require-jsdoc rule: Allow empty line after JS Doc

### ISSUE THREAD

**Issue by iusesoftware** [gajus/eslint-plugin-jsdoc#326] opened 2019-07-09 15:55 UTC
Hello there,

Thank you for the plugin.

Currently, the following block of code returns the following exception:

```
/**
 * JS Doc rules!
 */

function ignoreEmptyLineAbove() {
    rule();
}
```

```
 5:1  error  Missing JSDoc comment                                          jsdoc/require-jsdoc
```

Is there a way to make the plugin ignore the empty line after JS Doc / before the statement?

**Comment by golopot** [comment] 2019-07-09 17:04
Duplicate of #323

**Closed by golopot** 2019-07-09 17:04 UTC
