### ISSUE TITLE
`licensePattern` configuration accepts any string if pattern match fails

### ISSUE THREAD

**Issue by dennismphil** [gajus/eslint-plugin-jsdoc#885] opened 2022-04-26 17:49 UTC
### No `licensePattern` - Shows error 

![2022-04-26_10-41-53](https://user-images.githubusercontent.com/4141366/165361274-0fb285d7-580f-4411-82d3-e1cbb0af2f92.png)

### With licensePattern - Shows no error

![2022-04-26_10-42-36](https://user-images.githubusercontent.com/4141366/165361433-0b93f4bf-818e-4e70-9e44-a73da9663996.png)

## Environment

- Node version: 17.9.0   
- ESLint version 8.12.0
- `eslint-plugin-jsdoc` version: 39.2.9

**Comment by brettz9** [comment] 2022-04-26 22:40
Yes, this change was made by design as part of #884.

(The previous behavior had not been documented as such, so I tweaked it to allow for the regex to allow for opting out.)

The match now is intended to capture the area to be validated, so if you want to ensure that missing license patterns are caught, you should design your regex to eagerly match content (e.g., by use of `|` and/or `*`).

Closing as that should address though feel free to comment further as needed.

**Comment by dennismphil** [comment] 2022-04-26 22:55
@brettz9 Thanks for the response.

Here the pattern to match is provided as "black". The linter is not failing even if the given pattern is missing.

**Closed** 2022-04-26 22:57 UTC
Labels: bug-unconfirmed

**Comment by brettz9** [comment] 2022-04-26 22:58
The regex is just to find the zone which ought to identify any string area to be checked. If a zone is not found, then it is treated as valid.

**Comment by dennismphil** [comment] 2022-04-26 23:00
How do we enforce a particular string pattern to be present in the license block?

**Comment by brettz9** [comment] 2022-04-26 23:02
You should I think be able to use `jsdoc/match-description` for such.

**Comment by dennismphil** [comment] 2022-04-26 23:08
I believe that is for the description field. 

Feedback: The current implementation of \`licensePattern\` is not quite intuitive. One would expect a pattern to match with a given string.

**Comment by brettz9** [comment] 2022-04-26 23:39
`match-description` can be used with specific tags, including `@license`. Use the `tags` option.

Regarding the feedback, we can add more descriptive text in the docs, but I believe we need some way to define a zone such that missing matches can pass validation.
