### ISSUE TITLE
Referencing typedef from another module is not working

### ISSUE THREAD

**Issue by rashid301** [gajus/eslint-plugin-jsdoc#448] opened 2019-12-19 07:39 UTC
<img width="913" alt="Screenshot 2019-12-19 at 1 05 47 PM" src="https://user-images.githubusercontent.com/4918567/71153936-65e60680-2260-11ea-99d0-20fac61afc2a.png">

The top line contains the reference path. Typescript server is able to resolve it. But jsdoc complains about undefined type.

Plugin version: "eslint-plugin-jsdoc": "^18.4.3"

**Comment by brettz9** [comment] 2019-12-19 08:43
Closing as dupe of #99. Please Subscribe to that issue for any updates.

**Closed by brettz9** 2019-12-19 08:43 UTC
Labels: duplicate
