### ISSUE TITLE
The type 'TemplateStringsArray' is undefined.

### ISSUE THREAD

**Issue by rezyaev** [gajus/eslint-plugin-jsdoc#533] opened 2020-05-11 12:08 UTC
Modern JavaScript has [tagged template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates) feature. It is a function that allows processing of back ticks strings.

First argument for that function is of type `TemplateStringsArray`. And jsdoc plugin gives "The type 'TemplateStringsArray' is undefined." error when documenting it.

Example:
```js
/**
 * @param {TemplateStringsArray} strings // The type 'TemplateStringsArray' is undefined. eslint(jsdoc/no-undefined-types)
 * @param  {...any} expressions
 * @returns {string}
 */
export const html = (strings, ...expressions) =>
	strings
		.reduce((result, string, index) => {
			const expression = Array.isArray(expressions[index])
				? expressions[index].join('')
				: expressions[index];

			return expression
				? `${result}${string}${expression}`
				: `${result}${string}`;
		}, '')
		.replace(/(\t|\n)+/g, '');
```

Function usage:
```js
const world = 'world';
html`<div>Hello, ${world}</div>`; // '<div>Hello, world</div>'
```

**Comment by rezyaev** [comment] 2020-05-11 12:11
ESlint version: 7.0.0
Jsdoc-plugin version: 25.0.1
ESLint config:
```json
"plugins": ["immutable", "jsdoc"],
"env": {
	"browser": true,
	"es6": true
},
"parserOptions": {
	"ecmaVersion": 2020,
	"sourceType": "module"
}
```

**Comment by brettz9** [comment] 2020-05-11 14:03
This is not related to tagged templates being supported or not. The issue is that our code for the `jsdoc/no-undefined-types` rule currently relies on finding `TemplateStringsArray` as a defined (global) variable. Currently, you can workaround this by defining a `TemplateStringsArray` typedef in that file or adding it to `globals` in your config file or inline at the top of your file with `/* globals */`. 

For the ability for files to auto-detect which variables are in scope (e.g., if you have a class or typedef defined`TemplateStringsArray` somewhere in another file), you can follow #99 or #178 to follow about the desire for it to support local variables (e.g., if you had a non-global `TemplateStringsArray` class before you used the type).

Closing as that should resolve, though feel free to comment further as needed.

**Closed by brettz9** 2020-05-11 14:03 UTC

**Comment by rezyaev** [comment] 2020-05-11 14:29
Okay, thanks, i will add it to globals in config
